// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux not configured');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2bKbRvirvBXE9UCHQx12UyjGx5MSWuE',
    appId: '1:561951419562:android:cc5493d02641de6310f4d3',
    messagingSenderId: '561951419562',
    projectId: 'eco-track-afa87',
    storageBucket: 'eco-track-afa87.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApszEXTWVzixeFwtfHf4MQuZvD-oO4t0U',
    appId: '1:561951419562:web:a7236bcf8dce415610f4d3',
    messagingSenderId: '561951419562',
    projectId: 'eco-track-afa87',
    authDomain: 'eco-track-afa87.firebaseapp.com',
    storageBucket: 'eco-track-afa87.firebasestorage.app',
    measurementId: 'G-MVSV5RBNBX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO7YT47_eXUw2dT5jL3PettCf9-UtDcI8',
    appId: '1:561951419562:ios:7c4603953bc41d8a10f4d3',
    messagingSenderId: '561951419562',
    projectId: 'eco-track-afa87',
    storageBucket: 'eco-track-afa87.firebasestorage.app',
    iosBundleId: 'com.ecotrack.ecotrack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO7YT47_eXUw2dT5jL3PettCf9-UtDcI8',
    appId: '1:561951419562:ios:7c4603953bc41d8a10f4d3',
    messagingSenderId: '561951419562',
    projectId: 'eco-track-afa87',
    storageBucket: 'eco-track-afa87.firebasestorage.app',
    iosBundleId: 'com.ecotrack.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApszEXTWVzixeFwtfHf4MQuZvD-oO4t0U',
    appId: '1:561951419562:web:8b410d4d415dec8110f4d3',
    messagingSenderId: '561951419562',
    projectId: 'eco-track-afa87',
    authDomain: 'eco-track-afa87.firebaseapp.com',
    storageBucket: 'eco-track-afa87.firebasestorage.app',
    measurementId: 'G-XK4YZ62HR9',
  );

}